### ISSUE TITLE
Change default ports

### ISSUE THREAD

**Issue by johnsudaar** [ByteArena/ba#2]
It would be nice to provide a CLI option to change the default ports since `8081` and `8080` are often already used.

**Comment by xtuc** [comment]
You can specify a port by passing `--port PORT`. The visualization will listen on `PORT + 1`.

We should make the documentation clear enough about this.

**Comment by johnsudaar** [comment]
Right sorry

**Comment by xtuc** [comment]
I added a few lines in the [documentation](https://bytearena.com/doc/the-bytearena-cli).
