### ISSUE TITLE
`ba generate nodejs`: Makefile references wrong agent name

### ISSUE THREAD

**Issue by netgusto** [ByteArena/ba#22]
When using `ba generate nodejs`, the agent name built is not the one mentionned in the Makefile.

I see 4 possibilities here:

* leave it like that;
* remove the Makefile
* change the Makefile upon code generation to put in the correct name
* use `ba build` in the makefile with a default of `ba build` to use the current directory name as a docker tag

**Comment by xtuc** [comment]
The makefile was the old "API" for building the agent. I'll change it to ba build with uses the current directory as name.
