### ISSUE TITLE
Add the ability to expose custom port of the agent

### ISSUE THREAD

**Issue by johnsudaar** [ByteArena/ba#3]
It would be nice if the BA trainer can export some port of the agent (if you have an http server used for debugging)
or if you want to make a remote controlled agent to train your "real agent"

**Comment by netgusto** [comment]
There's the `-port` command line flag that's supposed to achieve that.
Or maybe I dont get it?

**Comment by netgusto** [comment]
ok got it: some port OF the agent.
Nevermind my previous comment.

**Comment by johnsudaar** [comment]
Yep!
Launching the container with `-P`, so we can define some exposed port in our `Dockerfile`:
https://docs.docker.com/engine/reference/builder/#expose

**Comment by xtuc** [comment]
That's ^ a good solution. On the trainer we allow these kind of Dockerfile instruction but online they will be forbidden.

We're going to consider doing something like that, thanks.

**Comment by xtuc** [comment]
Instead of the agent exposing a port/server, it can connect to whatever service you created.

Note that it will only be available in the trainer. @johnsudaar can we close this?

**Comment by netgusto** [comment]
Agent calling the host rather than the opposite: LGTM.

Especialy since many agents could connect to the same service.

**Comment by netgusto** [comment]
ping @johnsudaar
