### ISSUE TITLE
"git": executable file not found in $PATH

### ISSUE THREAD

**Issue by felipemanica** [ByteArena/ba#33]
```sh
ba generate nodejs
  ├ version: v0.0.8
  └ Failed to execute command
    ├ command: generate
    └ exec: "git": executable file not found in $PATH
      ├ error: 

```

**Comment by xtuc** [comment]
Thanks for your report. It seems that git is not installed on your machine.

You'll need to install it to generate an agent.

**Comment by netgusto** [comment]
On macOS you can install it from here: https://git-scm.com/download/mac
On Linux: https://git-scm.com/download/linux
