### ISSUE TITLE
Agent logs are not visible in the console

### ISSUE THREAD

**Issue by xtuc** [ByteArena/ba#4]
You need to emit a `\n` to be able to show the logs of your agent in the console.

We should show the logs whenever the agent logs a character.

**Comment by xtuc** [comment]
That's seems to be a Docker limitation.

**Comment by netgusto** [comment]
Source ?

**Comment by xtuc** [comment]
```sh
$ docker run -it node bash -c "node -e \"require('process').stdout.write('t');\" && sleep 100"
```

Docker logs against the running doesn't show anything until it finishes or you enter a new line manually.
