### ISSUE TITLE
ba generate fails on mint18

### ISSUE THREAD

**Issue by corpr8** [ByteArena/ba#41]
```sh
ba generate nodejs
  ├ version: v0.0.9
  └ Failed to execute command
    ├ command: generate
    └ ba build failed
      └ Unknown flag: from

```

**Comment by corpr8** [comment]
To be a bit more helpful:

Step 9/11 : COPY --from=0 /tmp/node_modules /usr/app/node_modules

❌  An error occurred.

ba generate nodejs
  ├ version: v0.0.9
  └ Failed to execute command
    ├ command: generate
    └ ba build failed
      └ Unknown flag: from

ls /usr/app
ls: cannot access '/usr/app': No such file or directory

ls /tmp/node_modules
ls: cannot access '/tmp/node_modules': No such file or directory

node --version
v9.2.1

4.4.0-21-generic #37-Ubuntu

**Comment by xtuc** [comment]
What version of Docker are you using? It seems that it doesn't support the multi-stage build Dockerfile we use here. 

Could you please update it to v17.05 or higher?

**Comment by corpr8** [comment]
That's got it - thanks, Happy new year :+1:
